name: spot
description: Chainable finders and better assertions for powerful widget tests.
version: 0.4.1
repository: https://github.com/passsy/spot
issue_tracker: https://github.com/passsy/spot/issues

environment:
  sdk: '>=3.0.0 <3.999.0'
  flutter: '>=3.10.0 <4.0.0'

dependencies:
  collection: ^1.17.0
  checks: ^0.3.0
  dartx: ^1.1.0
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  nanoid2: ^2.0.0
  test: ^1.24.0
  test_api: '>=0.5.0 <0.7.0'
  stack_trace: ^1.11.0

dependency_overrides:
  checks:
    git:
      url: https://github.com/dart-lang/test
      path: pkgs/checks
      ref: 7f81deeac294a1120917aeaa35d5b670146c4529

dev_dependencies:
  image: ^4.0.0
  lint: ^2.1.0
